# TiCDC Configuration for v7.1.0
# Most server options are passed as command line flags, not config file

[security]
# TLS configuration would go here if needed
# ca-path = ""
# cert-path = ""
# key-path = ""